let items1 = [
  {
    item: "Shirt",
    quantity: 20,
    price: 25,
    type: "Upper Body",
  },
  {
    item: "Pants",
    quantity: 15,
    price: 35,
    type: "Lower Body",
  },
  {
    item: "Dress",
    quantity: 10,
    price: 50,
    type: "One Piece",
  },
  {
    item: "Shoes",
    quantity: 5,
    price: 100,
    type: "Footwear",
  },
  {
    item: "Jacket",
    quantity: 10,
    price: 75,
    type: "Outerwear",
  },
  {
    item: "Skirt",
    quantity: 8,
    price: 30,
    type: "Lower Body",
  },
  {
    item: "Sunglasses",
    quantity: 12,
    price: 20,
    type: "Accessories",
  },
  {
    item: "Hat",
    quantity: 6,
    price: 15,
    type: "Accessories",
  },
  {
    item: "Belt",
    quantity: 9,
    price: 12,
    type: "Accessories",
  },
  {
    item: "Scarf",
    quantity: 7,
    price: 18,
    type: "Accessories",
  },
  {
    item: "T-Shirt",
    quantity: 20,
    price: 15,
    type: "Upper Body",
  },
  {
    item: "Jeans",
    quantity: 15,
    price: 40,
    type: "Lower Body",
  },
  {
    item: "Sweater",
    quantity: 10,
    price: 55,
    type: "Upper Body",
  },
  {
    item: "Sneakers",
    quantity: 5,
    price: 90,
    type: "Footwear",
  },
  {
    item: "Blazer",
    quantity: 8,
    price: 80,
    type: "Outerwear",
  },
  {
    item: "Shorts",
    quantity: 12,
    price: 20,
    type: "Lower Body",
  },
  {
    item: "Watch",
    quantity: 10,
    price: 50,
    type: "Accessories",
  },
  {
    item: "Earrings",
    quantity: 8,
    price: 12,
    type: "Accessories",
  },
  {
    item: "Necklace",
    quantity: 5,
    price: 20,
    type: "Accessories",
  },
  {
    item: "Bracelet",
    quantity: 7,
    price: 15,
    type: "Accessories",
  },
  {
    item: "Tank Top",
    quantity: 15,
    price: 10,
    type: "Upper Body",
  },
  {
    item: "Moschino Trousers",
    quantity: 15,
    price: 1000,
    type: "Lower Body",
  },
]

export {items1}
